---
- name: Check if awx password secret exists
  ansible.builtin.command: "{{ kubectl_command }} describe secret awx-admin-password -n awx"
  ignore_errors: true
  register: awx_password_secret
  failed_when: false
  changed_when: false
- name: Add awx password secret
  when: (awx_password_secret.rc != 0) and (awx_server_admin_password | length > 0)
  block:
    - name: Create AWX Secrets Directory
      become: true
      ansible.builtin.file:
        path: "{{ awx_project_directory }}/{{ awx_secrets_directory }}"
        state: directory
        mode: '0700'
        owner: "{{ ansible_user_id }}"
        group: "{{ linux_group }}"
    - name: Configure AWX Password
      ansible.builtin.template:
        src: "{{ awx_password_file }}.j2"
        dest: "{{ awx_project_directory }}/{{ awx_secrets_directory }}/{{ awx_password_file }}"
        mode: '0600'
    - name: Create awx password secret
      ansible.builtin.command: "{{ kubectl_command }} apply -f {{ awx_project_directory }}/{{ awx_secrets_directory }}/{{ awx_password_file }} -n awx"
      changed_when: true
    - name: Delete AWX Secrets Directory
      ansible.builtin.file:
        path: "{{ awx_project_directory }}/{{ awx_secrets_directory }}"
        state: absent
...
