---
- name: Check For existing Minikube Install
  ansible.builtin.stat:
    path: "{{ minikube_install_directory }}/minikube"
  register: minikube_install
- name: Check For existing K3s Install
  ansible.builtin.stat:
    path: "{{ k3s_install_directory }}/k3s"
  register: k3s_install
- name: Check For existing MicroK8s Install
  ansible.builtin.stat:
    path: "{{ microk8s_install_directory }}/microk8s"
  register: microk8s_install
- name: Install {{ awx_server_k8s_method }}
  ansible.builtin.include_tasks: "{{ awx_server_k8s_method }}.yml"
  when:
    - not minikube_install.stat.exists
    - not k3s_install.stat.exists
    - not microk8s_install.stat.exists
...
