---
- name: Get latest version number of the AWX operator
  ansible.builtin.uri:
    url: "{{ awx_release_url }}"
  register: awx_release
- name: Install prerequisite packages async task
  become: true
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - nginx
  async: 1000
  poll: 0
  register: prerequisite_packages_task
- name: Create AWX project directory
  ansible.builtin.file:
    path: "{{ awx_project_directory }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: docker
    mode: '755'
- name: Download docker signing key
  ansible.builtin.get_url:
    url: "{{ docker_key_url }}"
    dest: "{{ awx_project_directory }}/{{ gpg_keys_directory }}/docker.gpg"
    mode: '600'
- name: Check if docker key is already installed
  become: true
  ansible.builtin.stat:
    path: "{{ docker_keyring_file }}"
    checksum_algorithm: sha256
    get_checksum: true
  register: docker_gpg_key
- name: Block until prerequisite_packages_task is done
  become: true
  ansible.builtin.async_status:
    jid: "{{ prerequisite_packages_task.ansible_job_id }}"
  register: job1
  until: job1.finished
  retries: 100000
  delay: 1
- name: Open web port in firewall async task
  become: true
  community.general.ufw:
    rule: allow
    port: "{{ web_port }}"
    proto: tcp
    comment: Web port for AWX
  async: 1000
  poll: 0
  register: ufw_task
- name: Add docker apt repository async task
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by={{ docker_keyring_file }}] {{ docker_repo_url }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  async: 1000
  poll: 0
  register: docker_apt_repo_task
- name: Dearmor docker signing key
  become: true
  ansible.builtin.command: "gpg --yes -o {{ docker_keyring_file }} --dearmor {{ awx_project_directory }}/{{ gpg_keys_directory }}/docker.gpg"
  changed_when: true
  when: (docker_gpg_key.stat.checksum is undefined) or (docker_gpg_key.stat.checksum != 'a09e26b72228e330d55bf134b8eaca57365ef44bf70b8e27c5f55ea87a8b05e2')
- name: Block until docker_apt_repo_task is done
  become: true
  ansible.builtin.async_status:
    jid: "{{ docker_apt_repo_task.ansible_job_id }}"
  register: job2
  until: job2.finished
  retries: 100000
  delay: 1
- name: Block until prerequisite_packages_task is done
  become: true
  ansible.builtin.async_status:
    jid: "{{ prerequisite_packages_task.ansible_job_id }}"
  register: job3
  until: job3.finished
  retries: 100000
  delay: 1
- name: Install docker packages async task
  become: true
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
  async: 1000
  poll: 0
  register: docker_packages_task
- name: Disable nginx default host async task
  become: true
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  async: 1000
  poll: 0
  register: disable_nginx_host_task
- name: Configure nginx host file
  become: true
  ansible.builtin.template:
    src: awx_nginx.conf.j2
    dest: "/etc/nginx/sites-available/{{ nginx_config_name }}.conf"
    mode: '644'
- name: Enable nginx site
  become: true
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ nginx_config_name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ nginx_config_name }}.conf"
    state: link
- name: Block until disable_nginx_host_task is done
  become: true
  ansible.builtin.async_status:
    jid: "{{ disable_nginx_host_task.ansible_job_id }}"
  register: job4
  until: job4.finished
  retries: 100000
  delay: 1
- name: Restart nginx service async task
  become: true
  ansible.builtin.service:
    name: nginx
    enabled: true
    state: restarted
  async: 1000
  poll: 0
  register: restart_nginx_task
- name: Block until docker_packages_task is done
  become: true
  ansible.builtin.async_status:
    jid: "{{ docker_packages_task.ansible_job_id }}"
  register: job5
  until: job5.finished
  retries: 100000
  delay: 1
- name: Add ansible to docker group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true
- name: Install minikube
  become: true
  ansible.builtin.apt:
    deb: https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
- name: Configure minikube service
  ansible.builtin.template:
    src: minikube.service.j2
    dest: "{{ systemd_installation_directory }}/{{ minikube_service_name }}.service"
    mode: '644'
- name: Start and enable minikube service
  become: true
  ansible.builtin.service:
    daemon_reload: true
    name: "{{ minikube_service_name }}"
    enabled: true
    state: started
- name: Install kustomize
  become: true
  ansible.builtin.unarchive:
    src: "{{ kustomize_url }}"
    dest: "{{ kustomize_install_directory }}"
    remote_src: true
- name: Create AWX operator kustomization file
  ansible.builtin.template:
    src: operator_kustomization.j2
    dest: "{{ awx_project_directory }}/{{ awx_operator_kustomization_directory }}/kustomization.yaml"
    mode: '600'
- name: Check if base build file exists
  ansible.builtin.stat:
    path: "{{ awx_project_directory }}/awx-operator.yaml"
  register: base_build_file
- name: Build awx operator kustomize file
  ansible.builtin.command: "kustomize build {{ awx_project_directory }}/{{ awx_operator_kustomization_directory }}
    -o {{ awx_project_directory }}/awx-operator.yaml"
  when: not base_build_file.stat.exists
  changed_when: not base_build_file.stat.exists
- name: Check if awx operator already exists
  ansible.builtin.command: minikube kubectl -- get pods -l control-plane=controller-manager
    -n awx -o=jsonpath='{range .items[*]}{.status.containerStatuses[*].ready}{end}{"\n"}'
  register: awx_operator_status
  changed_when: false
- name: Build awx operator cluster
  ansible.builtin.command: "minikube kubectl -- apply -f {{ awx_project_directory }}/awx-operator.yaml"
  when: awx_operator_status.stdout != "true true"
  changed_when: awx_operator_status.stdout != "true true"
- name: Check if awx password secret exists
  ansible.builtin.command: "minikube kubectl -- describe secret awx-admin-password -n awx"
  ignore_errors: true
  register: awx_password_secret
  failed_when: false
  changed_when: false
- name: Add awx password secret
  when: awx_password_secret.rc != 0
  block:
    - name: Configure AWX password
      ansible.builtin.template:
        src: awx_password.yaml.j2
        dest: "{{ awx_project_directory }}/{{ awx_secrets_directory }}/awx_password.yaml"
        mode: '600'
    - name: Create AWX password secret
      ansible.builtin.command: "minikube kubectl -- apply -f {{ awx_project_directory }}/{{ awx_secrets_directory }}/awx_password.yaml -n awx"
      changed_when: true
    - name: Delete AWX secrets directory
      ansible.builtin.file:
        path: "{{ awx_project_directory }}/{{ awx_secrets_directory }}"
        state: absent
- name: Configure AWX instance async task
  ansible.builtin.template:
    src: awx.yaml.j2
    dest: "{{ awx_project_directory }}/{{ awx_kustomization_directory }}/awx.yaml"
    mode: '600'
- name: Create AWX instance kustomization file
  ansible.builtin.template:
    src: awx_kustomization.j2
    dest: "{{ awx_project_directory }}/{{ awx_kustomization_directory }}/kustomization.yaml"
    mode: '600'
  register: second_kustomize_file
- name: Build AWX instance kustomize file
  ansible.builtin.command: "kustomize build {{ awx_project_directory }}/{{ awx_kustomization_directory }} -o {{ awx_project_directory }}/awx-final.yaml"
  when: second_kustomize_file is changed # noqa: no-handler
  changed_when: second_kustomize_file is changed
- name: Check if awx instance already exists
  ansible.builtin.command: minikube kubectl -- get pods -l app.kubernetes.io/managed-by=awx-operator
    -n awx -o=jsonpath='{range .items[*]}{.status.containerStatuses[*].ready}{end}{"\n"}'
  register: awx_instance_status
  changed_when: false
- name: Build awx cluster
  ansible.builtin.command: "minikube kubectl -- apply -f {{ awx_project_directory }}/awx-final.yaml"
  when: (awx_instance_status.stdout != "true true true truetrue") or (second_kustomize_file is changed)
  changed_when: true # noqa: no-handler
- name: Block until restart_nginx_task is done
  become: true
  ansible.builtin.async_status:
    jid: "{{ restart_nginx_task.ansible_job_id }}"
  register: job10
  until: job10.finished
  retries: 100000
  delay: 1
- name: Block until ufw_task is done
  become: true
  ansible.builtin.async_status:
    jid: "{{ ufw_task.ansible_job_id }}"
  register: job11
  until: job11.finished
  retries: 100000
  delay: 1
- name: Wait for pods to be ready
  ansible.builtin.command: minikube kubectl -- get pods -l "app.kubernetes.io/managed-by=awx-operator"
    -n awx -o=jsonpath='{range .items[*]}{.status.containerStatuses[*].ready}{end}{"\n"}'
  register: awx_pods_status
  until: awx_pods_status.stdout == "truetrue true true truetrue true true"
  retries: 10000000
  delay: 10
  changed_when: false
- name: Wait for operator rollout to complete
  ansible.builtin.command: "minikube kubectl -- rollout status deployments/awx-operator-controller-manager -n awx -w"
  changed_when: false
- name: Wait for task rollout to complete
  ansible.builtin.command: "minikube kubectl -- rollout status deployments/awx-task -n awx -w"
  changed_when: false
- name: Wait for web rollout to complete
  ansible.builtin.command: "minikube kubectl -- rollout status deployments/awx-web -n awx -w"
  changed_when: false
- name: Wait for URL to be accessible
  ansible.builtin.uri:
    url: "http://{{ ansible_facts['fqdn'] }}"
    status_code: 200
  register: awx_url
  until: awx_url.status == 200
  retries: 100000
  delay: 10
  changed_when: false
...
