---
- name: Use UFW
  ansible.builtin.include_tasks: ufw.yml
  when: firewall_method == "UFW"
- name: Use Firewalld
  ansible.builtin.include_tasks: firewalld.yml
  when: firewall_method == "Firewalld"
- name: Use IPTables
  ansible.builtin.include_tasks: iptables.yml
  when: firewall_method == "IPTables"
- name: Use NFTables
  ansible.builtin.include_tasks: nftables.yml
  when: firewall_method == "NFTables"
...
