---
- name: Check if awx password secret exists
  ansible.builtin.command: "{{ kubectl_mapping[k8s_method] }} describe secret awx-admin-password -n awx"
  ignore_errors: true
  register: awx_password_secret
  failed_when: false
  changed_when: false
- name: Add awx password secret
  when: awx_password_secret.rc != 0
  block:
    - name: Configure awx password
      ansible.builtin.blockinfile:
        create: true
        mode: '600'
        path: "{{ awx_project_directory }}/{{ awx_secrets_directory }}/awx-password.yaml"
        block: |
          apiVersion: v1
          kind: Secret
          metadata:
            name: awx-admin-password
          type: Opaque
          data:
            password: "{{ awx_root_password | ansible.builtin.b64encode }}"
    - name: Create awx password secret
      ansible.builtin.command: "{{ kubectl_mapping[k8s_method] }} apply -f {{ awx_project_directory }}/{{ awx_secrets_directory }}/awx-password.yaml -n awx"
      changed_when: true
    - name: Delete AWX Secrets Directory
      ansible.builtin.file:
        path: "{{ awx_project_directory }}/{{ awx_secrets_directory }}"
        state: absent
...
