---
- name: Get latest version number of kustomize
  ansible.builtin.uri:
    url: "{{ github_release_base }}/{{ github_account }}/{{ github_repo }}/{{ github_release_end }}"
  vars:
    github_account: kubernetes-sigs
    github_repo: kustomize
  register: kustomize_release
- name: Install Kustomize
  become: true
  ansible.builtin.unarchive:
    mode: '0755'
    src: "{{ kustomize_download }}"
    dest: "{{ kustomize_install_directory }}"
    remote_src: true
  vars:
    github_account: kubernetes-sigs
    github_repo: kustomize
    kustomize_version: "{{ kustomize_release.json.tag_name | split('/') | last }}"
    release_file:
      "{{ github_repo }}_{{ kustomize_version
      }}_{{ mapping[ansible_facts['system']]
      }}_{{ mapping[ansible_facts['architecture']] }}.tar.gz"
    kustomize_download:
      "{{ github_base }}/{{ github_account }}/{{ github_repo }}/{{ github_download }}/{{ github_repo }}/{{ kustomize_version }}/{{ release_file }}"
...
