---
- name: Install Docker on Ubuntu
  ansible.builtin.include_tasks: docker-on-ubuntu.yml
- name: Configure minikube service
  become: true
  ansible.builtin.template:
    src: minikube.service.j2
    dest: "{{ systemd_installation_directory }}/minikube.service"
    mode: '644'
  register: minikube_service
- name: Systemctl Daemon Reload
  become: true
  ansible.builtin.service:
    daemon_reload: true
  when: minikube_service is changed # noqa: no-handler
  changed_when: minikube_service is changed
- name: Install minikube
  become: true
  ansible.builtin.apt:
    deb: "https://storage.googleapis.com/minikube/releases/latest/minikube_latest_{{ architecture_mapping[ansible_facts['architecture']] }}.deb"
- name: Start and enable minikube service
  become: true
  ansible.builtin.service:
    name: minikube
    enabled: true
    state: started
...
