---
amount_of_ram: 6g
no_of_cpus: 4
awx_project_directory: "/opt/awx"
web_port: 80
awx_release_url: https://api.github.com/repos/ansible/awx-operator/releases/latest
docker_ubuntu_key_url: https://download.docker.com/linux/ubuntu/gpg
docker_apt_keyring_file: /etc/apt/keyrings/docker.gpg
docker_ubuntu_repo_url: https://download.docker.com/linux/ubuntu
awx_operator_kustomization_directory: operator
awx_operator_kustomized: awx-operator.yml
awx_kustomization_directory: kustomize
awx_instance_file: awx.yml
awx_instance_kustomization: kustomization.yml
awx_instance_kustomized: awx-final.yml
awx_password_file: awx_password.yml
awx_secrets_directory: secrets
github_base: "https://github.com"
github_release_base: "https://api.github.com/repos"
github_release_end: "releases/latest"
github_download: "releases/download"
gpg_keys_directory: keys
k3s_url: "https://get.k3s.io"
k3s_install_directory: /usr/local/bin
kubectl_install_directory: /usr/local/bin
kubectl_command: kubectl
kustomize_install_directory: /usr/local/bin
linux_group: nogroup
microk8s_install_directory: /snap/bin
minikube_install_directory: /usr/local/bin
minikube_service_name: minikube
nginx_config_name: awx
nodeport_port: 30080
systemd_installation_directory: /etc/systemd/system
mapping:
  x86_64: amd64
  armv6l: armhf
  armv7l: armhf
  aarch64: arm64
  i386: i386
  ppc64: ppc64le
  s390x: x390x
  Linux: linux
...
